// Auto-generated QR V1 data modules for payload "483291"
// Generated by generate_qr_test.py — do not edit
#pragma once

#include <array>

namespace YipOS {
namespace QRTest {

static constexpr int QR_TEMPLATE_MACRO = 37;
static constexpr int QR_OFFSET = 5;
static constexpr int QR_SIZE = 21;
static constexpr int VQ_BLACK = 0;
static constexpr int VQ_WHITE = 255;

// Light data modules to write (VQ_WHITE) after template stamp
// Template leaves data area as background (dark), so we write light modules
static constexpr int LIGHT_MODULE_COUNT = 90;
struct Module { int col; int row; };
static constexpr std::array<Module, 90> LIGHT_MODULES = {{
    {14, 5},
    {17, 5},
    {15, 6},
    {16, 6},
    {16, 7},
    {14, 8},
    {17, 8},
    {15, 9},
    {15, 10},
    {16, 10},
    {17, 12},
    {14, 13},
    {15, 13},
    {5, 14},
    {8, 14},
    {9, 14},
    {10, 14},
    {13, 14},
    {14, 14},
    {15, 14},
    {16, 14},
    {17, 14},
    {18, 14},
    {21, 14},
    {23, 14},
    {5, 15},
    {7, 15},
    {8, 15},
    {10, 15},
    {15, 15},
    {18, 15},
    {5, 16},
    {9, 16},
    {10, 16},
    {13, 16},
    {14, 16},
    {15, 16},
    {16, 16},
    {19, 16},
    {21, 16},
    {22, 16},
    {24, 16},
    {7, 17},
    {8, 17},
    {10, 17},
    {12, 17},
    {14, 17},
    {16, 17},
    {17, 17},
    {19, 17},
    {24, 17},
    {25, 17},
    {19, 18},
    {20, 18},
    {21, 18},
    {25, 18},
    {18, 19},
    {19, 19},
    {20, 19},
    {21, 19},
    {25, 19},
    {18, 20},
    {19, 20},
    {20, 20},
    {22, 20},
    {23, 20},
    {25, 20},
    {14, 21},
    {18, 21},
    {20, 21},
    {21, 21},
    {15, 22},
    {17, 22},
    {18, 22},
    {21, 22},
    {24, 22},
    {25, 22},
    {14, 23},
    {15, 23},
    {16, 23},
    {17, 23},
    {23, 23},
    {17, 24},
    {18, 24},
    {19, 24},
    {21, 24},
    {25, 24},
    {15, 25},
    {16, 25},
    {17, 25}
}};

// Dark data modules (for reference — these are already background)
static constexpr int DARK_MODULE_COUNT = 118;

// Total data modules: 208 (90 light + 118 dark)
// Estimated render time: 1 macro stamp + 90 writes × 70ms ≈ 6.3s

} // namespace QRTest
} // namespace YipOS
